
data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 84
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 #delete_chans: [15,16,17,18,19,20,21,22,23,24,63,64,65,71,72,73,74,75,76,77,84,85,86,87]
 delete_chans: [75,84,85,86]
 transform_default:
  chans: []
  transform: []


 files_train: ["/data/nlahaye/remoteSensing/MASTER/MASTER_EMAS_Fuse2.npy"]

 files_test: ["/data/nlahaye/remoteSensing/MASTER/MASTER_EMAS_Fuse1.npy"]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MASTER_EMAS_FUSE/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"

dbn:
 subset_training: 1000000
 deep_cluster: 800
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [3000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [5] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.0] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [False]
  normalize_learnergy: [False]
  batch_normalize: [False]


 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["4","5"]
  batch_size: 512
  epochs: [100] #[8] #, 1, 1] #, 5] #, 10]


