files_train: "/home/nlahaye/Multi_Layer_Test/output/Learnergy/DBN_MISR_MODIS_1/output.data"
files_test: "/home/nlahaye/Multi_Layer_Test/output/Learnergy/DBN_MISR_MODIS_1/output_test.data"
 

output:
 out_dir: "output/Learnergy/DBN_MISR_MODIS_1/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 1500000
        clustering:
        train: True
        reset_n_clusters: True
        model:  


scaler:
 name: "standard_dask"
 scale: True
