files_train: [
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file89_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file8_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file90_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file9_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file100_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file101_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file102_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file103_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file104_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file105_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file106_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file107_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file108_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file109_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file10_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file110_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file111_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file112_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file113_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file114_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file115_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file116_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file117_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file118_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file119_output.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file90_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file9_output.data"]




output:
 out_dir: "/data/nlahaye/output/Learnergy/SAVE_LOAD_TEST/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-15
        pixel_padding: 1
        train_sample_size: 50000
        clustering: "/data/nlahaye/output/Learnergy/SAVE_LOAD_TEST/clustering.pkl"
        train: True
        reset_n_clusters: True
        chunks: 4
        model:  

scaler:
 name: "standard"
 scale: True

