high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: ["/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220322_114800_FULL.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220323_113000_FULL.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220323_113000_FULL.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220325_105400_FULL.npy"]
  geo_filenames: ["/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220322_114800_FULL.npy.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220323_113000_FULL.npy.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220324_111200_FULL.npy.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220325_105400_FULL.npy.lonlat.npy"]
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1

low_res:
 data:
  valid_min: 0.0
  valid_max: 240
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: ["/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220322_114000_wgs84_fit.tif.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220323_104500_wgs84_fit.tif.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220324_112500_wgs84_fit.tif.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220325_103000_wgs84_fit.tif.npy"]
  geo_filenames: ["/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220322_114000_wgs84_fit.tif.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220323_104500_wgs84_fit.tif.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220324_112500_wgs84_fit.tif.lonlat.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220325_103000_wgs84_fit.tif.lonlat.npy"]
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1

fusion:
 projection_id: "viirs_fusion"
 description: "resampling high res VIIRS channels to moderate resolution"
 area_id: "GERD Dam"
 projection_proj4:
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.009
 projection_units: "degrees"
 resample_radius: 5000
 resample_n_neighbors: 64
 resample_n_procs: 10
      
output_files: ["/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS_Fuse/viirs_modis_20220322_114800.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS_Fuse/viirs_modis_20220323_113000.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS_Fuse/viirs_modis_20220323_113000.npy",
"/media/mlat_data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS_Fuse/viirs_modis_20220325_105400.npy"]
 


