
data:
 pixel_padding: 1
 number_channels: 73
 fill_value: 0.0
 valid_min: -10.0
 valid_max:
 reader_type: "numpy"
 chan_dim: 0
 delete_chans: [66]
 transform_default:
  chans: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 60, 71, 72, 73]
  transform: [-2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0]

output:
 out_dir: "output/Learnergy/DBN_MISR_MODIS_1/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn.pth"

dbn:
 params:
  model_type: "variance_gaussian"
  dbn_arch: [2000]
  gibbs_steps: [10]
  learning_rate: [0.01]
  momentum: [0.95]
  decay: [0.0001]
  temp: [0.5]

 training:
  use_gpu: False
  batch_size: 10
  epochs: [1]
