files_train: ["/data/nlahaye/output/Learnergy/DBN_S3_GERD/file1_output.data"] #, "/data/nlahaye/output/Learnergy/DBN_S3_GERD/file1_output.data"]
files_test: ["/data/nlahaye/output/Learnergy/DBN_S3_GERD/file0_output_test.data", "/data/nlahaye/output/Learnergy/DBN_S3_GERD/file1_output_test.data", "/data/nlahaye/output/Learnergy/DBN_S3_GERD/file2_output_test.data", "/data/nlahaye/output/Learnergy/DBN_S3_GERD/file3_output_test.data", "/data/nlahaye/output/Learnergy/DBN_S3_GERD/file0_output.data"]
 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_S3_GERD/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 1500000
        number_train_epochs: 40
        predict_data_chunk: 10000
        clustering:
        train: True
        reset_n_clusters: True
        model:  

