
data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[]]
 create_seperate: true
 
 gtiff_data: ["/data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220322_114000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220323_104500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/GERD_DAM/MODIS/aqua_modis_bt36_20220325_103000_wgs84_fit.tif"]
 cluster_fnames: ["/data/nlahaye/output/Learnergy/DBN_VIIRS_MODIS/file0_output.data.clustering.zarr",
"/data/nlahaye/output/Learnergy/DBN_VIIRS_MODIS/file1_output.data.clustering.zarr",
"/data/nlahaye/output/Learnergy/DBN_VIIRS_MODIS/file0_output_test.data.clustering.zarr"]
 

context:
 apply_context: false
 clusters: [] #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false


