

data:
 #filename: ["/data/nlahaye/remoteSensing/Palm_Oil/Contour_Test/Palm_Oil_Test_V2.tif"]
 filename: [
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_08_20190806_1834_1846_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_10_20190806_1858_1910_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_13_20190806_1923_1925_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_14_20190806_1926_1929_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_15_20190806_1931_1938_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_16_20190806_1941_1956_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_17_20190806_2000_2010_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_18_20190806_2018_2031_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_19_20190806_2035_2048_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_20_20190806_2052_2106_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19910_21_20190806_2111_2125_V02_Georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_05_20190807_1817_1833_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_08_20190807_1928_1942_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_09_20190807_1947_2002_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_10_20190807_2004_2016_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_11_20190807_2021_2035_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19911_12_20190807_2039_2051_V02_georeferenced_scaled_SmokeMask_v13.tif",
"/data/nlahaye/remoteSensing/eMAS/detect_030/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled_SmokeMask_v13.tif"
]
 reader_type: "gtiff"
 reader_kwargs:
  None:

remove_singles: True
write_geotiff: True

