
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[]]
 create_separate: true


 gtiff_data: [
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/new_tile/HLS.S30.T30TYQ.2022345T105339.v2.0.B01.tif"]



 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file1_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file2_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file3_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file4_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file5_output_test.data.clustering_500clusters.zarr"]

   
 
context:
 apply_context: true
 clusters: [292, 10]
 name: "Water" #i.e. smoke
 compare_truth: false
 generate_union: 3


